import dynamic from 'next/dynamic';
import { IThemeColor, ITemplate } from './index.interface';

export const SYSTEM_COLORS: IThemeColor[] = [
  {
    backgroundColor: 'white',
    fontColor: 'black',
    titleColor: '#1890ff',
    highlighterColor: 'yellowgreen',
    id: 1,
  },
  {
    backgroundColor: 'white',
    fontColor: '#780650',
    titleColor: '#254000',
    highlighterColor: 'burlywood',
    id: 2,
  },
  {
    backgroundColor: '#FFFFFF',
    fontColor: '#000000',
    titleColor: '#217503',
    highlighterColor: '#F556E5',
    id: 3,
  },

  {
    backgroundColor: 'white',
    fontColor: '#000000',
    titleColor: '#1A1A1A',
    highlighterColor: '#FF0080',
    id: 4,
  },
  {
    backgroundColor: 'white',
    fontColor: '#0A0A0A',
    titleColor: '#2C2C2C',
    highlighterColor: '#FF6B35',
    id: 5,
  },
  {
    backgroundColor: 'white',
    fontColor: '#141414',
    titleColor: '#3A3A3A',
    highlighterColor: '#FF1493',
    id: 6,
  },
  {
    backgroundColor: 'white',
    fontColor: '#1A1A1A',
    titleColor: '#4A4A4A',
    highlighterColor: '#4ECDC4',
    id: 7,
  },
  {
    backgroundColor: 'white',
    fontColor: '#1E1E1E',
    titleColor: '#5A5A5A',
    highlighterColor: '#FFE066',
    id: 8,
  },

  {
    backgroundColor: 'white',
    fontColor: '#2C2C2C',
    titleColor: '#1B1B1B',
    highlighterColor: '#FF6B6B',
    id: 9,
  },
  {
    backgroundColor: 'white',
    fontColor: '#3A3A3A',
    titleColor: '#2A2A2A',
    highlighterColor: '#4ECDC4',
    id: 10,
  },
  {
    backgroundColor: 'white',
    fontColor: '#1E2124',
    titleColor: '#36393F',
    highlighterColor: '#7289DA',
    id: 11,
  },
  {
    backgroundColor: 'white',
    fontColor: '#23272A',
    titleColor: '#2F3136',
    highlighterColor: '#43B581',
    id: 12,
  },
  {
    backgroundColor: 'white',
    fontColor: '#0D1117',
    titleColor: '#161B22',
    highlighterColor: '#F04747',
    id: 13,
  },

  {
    backgroundColor: 'white',
    fontColor: '#21262D',
    titleColor: '#24292F',
    highlighterColor: '#58A6FF',
    id: 14,
  },
  {
    backgroundColor: 'white',
    fontColor: '#1C2128',
    titleColor: '#1B1F23',
    highlighterColor: '#7C3AED',
    id: 15,
  },
  {
    backgroundColor: 'white',
    fontColor: '#282C34',
    titleColor: '#2D3748',
    highlighterColor: '#61DAFB',
    id: 16,
  },
  {
    backgroundColor: 'white',
    fontColor: '#1A202C',
    titleColor: '#2A4365',
    highlighterColor: '#4FD1C7',
    id: 17,
  },
  {
    backgroundColor: 'white',
    fontColor: '#4A5568',
    titleColor: '#1A365D',
    highlighterColor: '#F6AD55',
    id: 18,
  },

  {
    backgroundColor: 'white',
    fontColor: '#2C5282',
    titleColor: '#2A2D3A',
    highlighterColor: '#68D391',
    id: 19,
  },
  {
    backgroundColor: 'white',
    fontColor: '#1B1B2F',
    titleColor: '#162447',
    highlighterColor: '#BB86FC',
    id: 20,
  },
  {
    backgroundColor: 'white',
    fontColor: '#2D3748',
    titleColor: '#4A5568',
    highlighterColor: '#9F7AEA',
    id: 21,
  },
  {
    backgroundColor: 'white',
    fontColor: '#1A202C',
    titleColor: '#2A4365',
    highlighterColor: '#4299E1',
    id: 22,
  },
  {
    backgroundColor: 'white',
    fontColor: '#3C366B',
    titleColor: '#553C9A',
    highlighterColor: '#F6E05E',
    id: 23,
  },

  {
    backgroundColor: 'white',
    fontColor: '#744210',
    titleColor: '#8B4513',
    highlighterColor: '#4FD1C7',
    id: 24,
  },
  {
    backgroundColor: 'white',
    fontColor: '#742A2A',
    titleColor: '#97266D',
    highlighterColor: '#FBD38D',
    id: 25,
  },
  {
    backgroundColor: 'white',
    fontColor: '#22543D',
    titleColor: '#234E52',
    highlighterColor: '#68D391',
    id: 26,
  },
  {
    backgroundColor: 'white',
    fontColor: '#2A4365',
    titleColor: '#1A365D',
    highlighterColor: '#FED7E2',
    id: 27,
  },
  {
    backgroundColor: 'white',
    fontColor: '#4A148C',
    titleColor: '#6B46C1',
    highlighterColor: '#BB86FC',
    id: 28,
  },

  {
    backgroundColor: 'white',
    fontColor: '#1B5E20',
    titleColor: '#2E7D32',
    highlighterColor: '#03DAC6',
    id: 29,
  },
  {
    backgroundColor: 'white',
    fontColor: '#E65100',
    titleColor: '#F57C00',
    highlighterColor: '#E43F5A',
    id: 30,
  },
  {
    backgroundColor: 'white',
    fontColor: '#C62828',
    titleColor: '#D32F2F',
    highlighterColor: '#F38BA8',
    id: 31,
  },
  {
    backgroundColor: 'white',
    fontColor: '#AD1457',
    titleColor: '#C2185B',
    highlighterColor: '#1F883D',
    id: 32,
  },
  {
    backgroundColor: 'white',
    fontColor: '#0D47A1',
    titleColor: '#1565C0',
    highlighterColor: '#28A745',
    id: 33,
  },

  {
    backgroundColor: 'white',
    fontColor: '#1565C0',
    titleColor: '#1976D2',
    highlighterColor: '#E53E3E',
    id: 34,
  },
  {
    backgroundColor: 'white',
    fontColor: '#7B1FA2',
    titleColor: '#8E24AA',
    highlighterColor: '#48BB78',
    id: 35,
  },
  {
    backgroundColor: 'white',
    fontColor: '#388E3C',
    titleColor: '#43A047',
    highlighterColor: '#9F7AEA',
    id: 36,
  },
  {
    backgroundColor: 'white',
    fontColor: '#F57C00',
    titleColor: '#FF9800',
    highlighterColor: '#4FD1C7',
    id: 37,
  },
  {
    backgroundColor: 'white',
    fontColor: '#D32F2F',
    titleColor: '#F44336',
    highlighterColor: '#805AD5',
    id: 38,
  },

  {
    backgroundColor: 'white',
    fontColor: '#C2185B',
    titleColor: '#E91E63',
    highlighterColor: '#38B2AC',
    id: 39,
  },
  {
    backgroundColor: 'white',
    fontColor: '#303F9F',
    titleColor: '#3F51B5',
    highlighterColor: '#ED8936',
    id: 40,
  },
  {
    backgroundColor: 'white',
    fontColor: '#00796B',
    titleColor: '#009688',
    highlighterColor: '#F56565',
    id: 41,
  },
  {
    backgroundColor: 'white',
    fontColor: '#689F38',
    titleColor: '#8BC34A',
    highlighterColor: '#7F9CF5',
    id: 42,
  },
  {
    backgroundColor: 'white',
    fontColor: '#AFB42B',
    titleColor: '#CDDC39',
    highlighterColor: '#F687B3',
    id: 43,
  },

  {
    backgroundColor: 'white',
    fontColor: '#FF8F00',
    titleColor: '#FFC107',
    highlighterColor: '#63B3ED',
    id: 44,
  },
  {
    backgroundColor: 'white',
    fontColor: '#FF6F00',
    titleColor: '#FF9800',
    highlighterColor: '#68D391',
    id: 45,
  },
  {
    backgroundColor: 'white',
    fontColor: '#E64A19',
    titleColor: '#FF5722',
    highlighterColor: '#B794F6',
    id: 46,
  },
  {
    backgroundColor: 'white',
    fontColor: '#D84315',
    titleColor: '#FF3D00',
    highlighterColor: '#4FD1C7',
    id: 47,
  },
  {
    backgroundColor: 'white',
    fontColor: '#BF360C',
    titleColor: '#DD2C00',
    highlighterColor: '#FCD34D',
    id: 48,
  },

  {
    backgroundColor: 'white',
    fontColor: '#33691E',
    titleColor: '#558B2F',
    highlighterColor: '#FFA07A',
    id: 49,
  },
  {
    backgroundColor: 'white',
    fontColor: '#1B5E20',
    titleColor: '#2E7D32',
    highlighterColor: '#FFE066',
    id: 50,
  },
  {
    backgroundColor: 'white',
    fontColor: '#064E3B',
    titleColor: '#059669',
    highlighterColor: '#FCD34D',
    id: 51,
  },
  {
    backgroundColor: 'white',
    fontColor: '#1E3A8A',
    titleColor: '#2563EB',
    highlighterColor: '#93C5FD',
    id: 52,
  },
  {
    backgroundColor: 'white',
    fontColor: '#7C2D12',
    titleColor: '#EA580C',
    highlighterColor: '#FDBA74',
    id: 53,
  },
  {
    backgroundColor: 'white',
    fontColor: '#4C1D95',
    titleColor: '#7C3AED',
    highlighterColor: '#C4B5FD',
    id: 54,
  },
  {
    backgroundColor: 'white',
    fontColor: '#134E4A',
    titleColor: '#0D9488',
    highlighterColor: '#2DD4BF',
    id: 55,
  },
  {
    backgroundColor: 'white',
    fontColor: '#374151',
    titleColor: '#4B5563',
    highlighterColor: '#9CA3AF',
    id: 56,
  },
  {
    backgroundColor: 'white',
    fontColor: '#7F1D1D',
    titleColor: '#DC2626',
    highlighterColor: '#F87171',
    id: 57,
  },
  {
    backgroundColor: 'white',
    fontColor: '#365314',
    titleColor: '#65A30D',
    highlighterColor: '#BEF264',
    id: 58,
  },
  {
    backgroundColor: 'white',
    fontColor: '#1E1B4B',
    titleColor: '#4338CA',
    highlighterColor: '#818CF8',
    id: 59,
  },
  {
    backgroundColor: 'white',
    fontColor: '#831843',
    titleColor: '#DB2777',
    highlighterColor: '#F472B6',
    id: 60,
  },
  {
    backgroundColor: 'white',
    fontColor: '#451A03',
    titleColor: '#92400E',
    highlighterColor: '#F59E0B',
    id: 61,
  },
  {
    backgroundColor: 'white',
    fontColor: '#0F172A',
    titleColor: '#334155',
    highlighterColor: '#64748B',
    id: 62,
  },
  {
    backgroundColor: 'white',
    fontColor: '#581C87',
    titleColor: '#9333EA',
    highlighterColor: '#D8B4FE',
    id: 63,
  },
  {
    backgroundColor: 'white',
    fontColor: '#064E3B',
    titleColor: '#10B981',
    highlighterColor: '#6EE7B7',
    id: 64,
  },
  {
    backgroundColor: 'white',
    fontColor: '#450A0A',
    titleColor: '#991B1B',
    highlighterColor: '#EF4444',
    id: 65,
  },
];

export const AVAILABLE_TEMPLATES: ITemplate = {
  modern: {
    id: 'modern',
    name: 'Velocity Elite',
    thumbnail: '/templates/1.jpg',
    component: dynamic(() => import('@/templates/modern/MordernTemplate'), {
      ssr: false,
    }),
  },
  professional: {
    id: 'professional',
    name: 'Corporate Pulse',
    thumbnail: '/templates/2.jpg',
    component: dynamic(() => import('@/templates/professional/ProfessionalTemplate'), {
      ssr: false,
    }),
  },
  executive: {
    id: 'executive',
    name: 'Zenith Peak',
    thumbnail: '/templates/3.jpg',
    component: dynamic(() => import('@/templates/executive/ExecutiveTemplate'), {
      ssr: false,
    }),
  },
  compact: {
    id: 'compact',
    name: 'Quantum Slice',
    thumbnail: '/templates/4.jpg',
    component: dynamic(() => import('@/templates/compact/CompactTemplate')),
  },
  elegant: {
    id: 'elegant',
    name: 'Ethereal Flow',
    thumbnail: '/templates/5.jpg',
    component: dynamic(() => import('@/templates/elegant/ElegantTemplate')),
  },
  contemporary: {
    id: 'contemporary',
    name: 'Nexus Grid',
    thumbnail: '/templates/6.jpg',
    component: dynamic(() => import('@/templates/contemporary/ContemporaryTemplate')),
  },
  navy: {
    id: 'navy',
    name: 'Deep Ocean',
    thumbnail: '/templates/navy.png',
    component: dynamic(() => import('@/templates/navy/NavyTemplate')),
  },
  minimal: {
    id: 'minimal',
    name: 'Stark Clarity',
    thumbnail: '/templates/minimal.png',
    component: dynamic(() => import('@/templates/minimal/MinimalTemplate')),
  },
  atlas: {
    id: 'atlas',
    name: 'Titan Map',
    thumbnail: '/templates/atlas.png',
    component: dynamic(() => import('@/templates/atlas/AtlasTemplate'), { ssr: false }),
  },
  santiago: {
    id: 'santiago',
    name: 'Iberian Soul',
    thumbnail: '/templates/santiago.png',
    component: dynamic(() => import('@/templates/santiago/santiagoTemplate'), {
      ssr: false,
    }),
  },
  prime: {
    id: 'prime',
    name: 'Optimus Prime',
    thumbnail: '/templates/prime.png',
    component: dynamic(() => import('@/templates/prime/PrimeTemplate'), {
      ssr: false,
    }),
  },
  berlin: {
    id: 'berlin',
    name: 'Metropolis Edge',
    thumbnail: '/templates/berlin.png',
    component: dynamic(() => import('@/templates/berlin/BerlinTemplate'), {
      ssr: false,
    }),
  },
  traditional: {
    id: 'traditional',
    name: 'Heritage Classic',
    thumbnail: '/templates/traditional.png',
    component: dynamic(() => import('@/templates/traditional/TraditionalTemplate'), { ssr: false }),
  },
  athens: {
    id: 'athens',
    name: 'Olympic Pillar',
    thumbnail: '/templates/athens.png',
    component: dynamic(() => import('@/templates/athens/AthensTemplate'), {
      ssr: false,
    }),
  },
  cambridge: {
    id: 'cambridge',
    name: "Scholar's Quill",
    thumbnail: '/templates/cambridge.png',
    component: dynamic(() => import('@/templates/cambridge/CambridgeTemplate'), { ssr: false }),
  },
  nova: {
    id: 'nova',
    name: 'Cosmic Spark',
    thumbnail: '/templates/nova.png',
    component: dynamic(() => import('@/templates/nova/NovaTemplate'), {
      ssr: false,
    }),
  },
  amsterdam: {
    id: 'amsterdam',
    name: 'Canal Vista',
    thumbnail: '/templates/amsterdam.png',
    component: dynamic(() => import('@/templates/amsterdam/amsterdam/AmstredamTemplate'), {
      ssr: false,
    }),
  },
  noble: {
    id: 'noble',
    name: "Aristocrat's Choice",
    thumbnail: '/templates/noble.png',
    component: dynamic(() => import('@/templates/noble/noble/NobleTemplate'), {
      ssr: false,
    }),
  },
  orbit: {
    id: 'orbit',
    name: 'Planetary Path',
    thumbnail: '/templates/orbit.png',
    component: dynamic(() => import('@/templates/orbit/orbit/OrbitTemplate'), {
      ssr: false,
    }),
  },
  shanghai: {
    id: 'shanghai',
    name: 'Oriental Skyline',
    thumbnail: '/templates/shanghai.png',
    component: dynamic(() => import('@/templates/shanghai/shanghai/ShanghaiTemplate'), {
      ssr: false,
    }),
  },
  brussels: {
    id: 'brussels',
    name: 'European Union',
    thumbnail: '/templates/brussels.png',
    component: dynamic(() => import('@/templates/brussels/BrusselsTemplate'), {
      ssr: false,
    }),
  },
  paris: {
    id: 'paris',
    name: 'Lumière Chic',
    thumbnail: '/templates/paris.png',
    component: dynamic(() => import('@/templates/paris/ParisTemplate'), {
      ssr: false,
    }),
  },
  'cyber-matrix': {
    id: 'cyber-matrix',
    name: 'Neural Grid (IT Special)',
    thumbnail: '/templates/cyber-matrix.png',
    component: dynamic(() => import('@/templates/cyber-matrix/CyberMatrixTemplate'), {
      ssr: false,
    }),
  },
  'academic-pro': {
    id: 'academic-pro',
    name: "Scholar's Edge (CS Student)",
    thumbnail: '/templates/paris.png',
    component: dynamic(() => import('@/templates/academic-pro/AcademicProTemplate'), {
      ssr: false,
    }),
  },
};

export const CUSTOM_THEME_COLOR: IThemeColor = {
  backgroundColor: 'white',
  fontColor: 'black',
  titleColor: 'green',
  highlighterColor: '#ff7875',
  id: 4,
};

export const DATE_PICKER_FORMAT = 'DD/MM/YYYY';
